/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mobaolibo_jni_bsdiff_DiffUtils */

#ifndef _Included_com_example_mobaolibo_jni_bsdiff_DiffUtils
#define _Included_com_example_mobaolibo_jni_bsdiff_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL
Java_com_mobao_utils_iupgrade_PatchUtils_patch
        (JNIEnv *, jclass, jstring, jstring, jstring);
}

#endif
