/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mobaolibo_jni_bsdiff_DiffUtils */

#ifndef _Included_com_example_mobaolibo_jni_bsdiff_DiffUtils
#define _Included_com_example_mobaolibo_jni_bsdiff_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mobaolibo_jni_bsdiff_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_mobaolibo_jni_bsdiff_PatchUtils_genDiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_yyh_lib_bsdiff_PatchUtils
 * Method:    genNewApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_mobaolibo_jni_bsdiff_PatchUtils_patch
        (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
